const COMPANY_DETAILS = 'COMPANY_DETAILS';
const SALES_DETAILS = 'SALES_DETAILS';
const CUSTOMER_DETAILS = 'CUSTOMER_DETAILS';

const actions = {
  COMPANY_DETAILS,
  SALES_DETAILS,
  CUSTOMER_DETAILS,
};

export default actions;